### ISSUE TITLE
Update pip Project?

### ISSUE THREAD

**Issue by burns1337** [INTO-CPS-Association/unifmu#58]
Firstly, Thx for your rich tool! 

I highly consider using your framework (and for sure contributing, in case i find some improvements) for my Masterthesis about EnergyPlus Co-Simulation.
May I ask you if it would be possible to update the pip source/project of UniFMU here https://pypi.org/project/unifmu/  e.g. to v0.0.6 or higher for easier cloning and implementing? I would highly appreciate this! 

And btw, may I ask on what you are working currently and what are your next "furture work" tasks or desired TODOs you would wish to get fullfilled (I ask this, to avoid redundant work and get a clue what's currently going on) ;)?

Thx in advance and
greetz burns

**Comment by clagms** [comment]
Hi @burns1337 , first thank you for your interest in the tool! 

Apologies for the delay.

Unfortunately since our tool is used in different backends and not just python we feel like it would be inconsistent to release it on Pypi and not release it in other package repositories. 

Unfortunately it is very easy for you to grab the latest release from the releases page. You can then place the binary anywhere where you can execute it and just run it to generate your FMU starting point.

As for next steps we are currently doing an overhaul in the tool and implementing fmi 3.0 with synchronous clocks. See https://github.com/INTO-CPS-Association/unifmu/issues/42
